# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------

HEADERS += ./client.h \
    ./userLogin.h
SOURCES += ./client.cpp \
    ./main.cpp \
    ./userLogin.cpp
FORMS += ./client.ui \
    ./userLogin.ui
RESOURCES += ./client.qrc
